[metadata]
creation_date = "2020/01/07"
maturity = "production"
updated_date = "2020/01/07"

[rule]
author = ["Elastic"]
description = "Identifies the execution of a Shell process with suspicious args that may indicate a reverse shell activity."
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "Potential Reverse Shell Activity via Terminal"
references = [
    """
    https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology and Resources/Reverse Shell
    Cheatsheet.md
    """,
    "https://github.com/WangYihang/Reverse-Shell-Manager",
]
risk_score = 73
rule_id = "a1a0375f-22c2-48c0-81a4-7c2d11cc6856"
severity = "high"
tags = ["Elastic", "Host", "Linux", "macOS", "Threat Detection", "Execution"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
 process.name in ("sh", "bash", "zsh", "dash", "zmodload") and
 wildcard(process.args, "/dev/tcp/*", "/dev/udp/*", "5<>/dev/tcp/*", ">/dev/tcp/*", ">/dev/udp/*", "zsh/net/tcp", "zsh/net/udp")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

