[metadata]
creation_date = "2020/01/11"
maturity = "production"
updated_date = "2020/01/11"

[rule]
author = ["Elastic"]
description = """
Identifies the creation of zip file starting with special chars in the Library folder. Adversaries may use this
technique to evade sandbox office application via writing a zipped payload that will be extracted (by Archive Utility)
to the the LaunchAgent folder upon user logon by combining it with a logon item set to run the zip file.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Potential Office Sandbox Evasion via LaunchAgent ZIP File"
references = [
    "https://i.blackhat.com/USA-20/Wednesday/us-20-Wardle-Office-Drama-On-macOS.pdf",
    "https://www.mdsec.co.uk/2018/08/escaping-the-sandbox-microsoft-office-on-macos/",
]
risk_score = 73
rule_id = "d22a85c6-d2ad-4cc4-bf7b-54787473669a"
severity = "high"
tags = ["Elastic", "Host", "macOS", "Threat Detection", "Defense Evasion", "Persistence"]
type = "query"

query = '''
event.category:file and not event.type:deletion and file.path:/Users/*/Library/~$*.zip
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1159"
name = "Launch Agent"
reference = "https://attack.mitre.org/techniques/T1159/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

