[metadata]
creation_date = "2020/12/22"
maturity = "production"
updated_date = "2020/12/22"

[rule]
author = ["Elastic"]
description = """
Identifies the use of a compression utility to collect known files containing sensitive information such as credentials
and system configurations.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "Sensitive Files Compression"
references = [
    "https://www.trendmicro.com/en_ca/research/20/l/teamtnt-now-deploying-ddos-capable-irc-bot-tntbotinger.html",
]
risk_score = 47
rule_id = "6b84d470-9036-4cc0-a27c-6d90bbfe81ab"
severity = "medium"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "Collection", "Credential Access"]
type = "eql"

query = '''
process where event.type in ("start", "process_started") and
 process.name in ("zip", "tar", "gzip", "hdiutil") and
  wildcard(process.args,
              "/root/.ssh/id_rsa",
              "/root/.ssh/id_rsa.pub",
              "/root/.ssh/id_ed25519",
              "/root/.ssh/id_ed25519.pub",
              "/root/.ssh/authorized_keys",
              "/root/.ssh/authorized_keys2",
              "/root/.ssh/known_hosts",
              "/root/.bash_history",
              "/etc/hosts",
              "/home/*/.ssh/id_rsa",
              "/home/*/.ssh/id_rsa.pub",
              "/home/*/.ssh/id_ed25519",
              "/home/*/.ssh/id_ed25519.pub",
              "/home/*/.ssh/authorized_keys",
              "/home/*/.ssh/authorized_keys2",
              "/home/*/.ssh/known_hosts",
              "/home/*/.bash_history",
              "/root/.aws/credentials",
              "/root/.aws/config",
              "/home/*/.aws/credentials",
              "/home/*/.aws/config",
              "/root/.docker/config.json",
              "/home/*/.docker/config.json",
              "/etc/group",
              "/etc/passwd",
              "/etc/shadow",
              "/etc/gshadow"
             )
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1552"
name = "Unsecured Credentials"
reference = "https://attack.mitre.org/techniques/T1552/"
[[rule.threat.technique.subtechnique]]
id = "T1552.001"
name = "Credentials In Files"
reference = "https://attack.mitre.org/techniques/T1552/001/"



[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1560"
name = "Archive Collected Data"
reference = "https://attack.mitre.org/techniques/T1560/"
[[rule.threat.technique.subtechnique]]
id = "T1560.001"
name = "Archive via Utility"
reference = "https://attack.mitre.org/techniques/T1560/001/"



[rule.threat.tactic]
id = "TA0009"
name = "Collection"
reference = "https://attack.mitre.org/tactics/TA0009/"

