[metadata]
creation_date = "2020/12/21"
maturity = "production"
updated_date = "2020/12/21"

[rule]
author = ["Elastic"]
description = """
Adversaries may modify the standard Unix authentication module for persistence via patching the normal authorization
process to allow unauthorized access.
"""
false_positives = ["Trused System Modules Updates"]
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "Modification of Unix Standard Authentication Module"
references = [
    "https://www.trendmicro.com/en_us/research/19/i/skidmap-linux-malware-uses-rootkit-capabilities-to-hide-cryptocurrency-mining-payload.html",
    "https://github.com/zephrax/linux-pam-backdoor",
]
risk_score = 47
rule_id = "93f47b6f-5728-4004-ba00-625083b3dcb0"
severity = "medium"
tags = ["Elastic", "Host", "Linux", "Threat Detection", "Persistence"]
type = "eql"

query = '''
file where event.type in ("creation", "change") and file.name:"pam_unix.so"
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1543"
name = "Create or Modify System Process"
reference = "https://attack.mitre.org/techniques/T1543/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

